/**
* File: define.hh
* Project: star_strek
* File Created: Monday, 10th July 2023 11:18:59 am
* Author: LALIN Romain 
* -----
* Last Modified: Thursday, 27th July 2023 9:18:08 pm
* Modified By: LALIN Romain
* -----
*/

#ifndef DEFINE_HH_
#define DEFINE_HH_

#include <map>

#define BDDFILE "bdd.json"
#define SEP "|"
#define CLEAR "cls"
#define MDP "je préfère le Faucon Millenium"
#define QUIDAMS vector<OBJETS> {HEROS, PNJ, EVIL}

typedef enum {
    ERROR_COMMAND = -1,
    INIT,
    ATTACK,
    EXCHANGE_ITEM,
    GET_INFOS,
    KILL,
    ESCAPE,
    ADD_ENTITIES,
    GET_HABITANTS,
    GET_EQUIPAGE,
    GET_INVENTORY,
    PROMOTE,
    GET_HIERARCHY
}   COMMANDS;

const std::map<COMMANDS, std::string> COMMANDS_LIST {
    {INIT, "init"},
    {ATTACK, "attack"},
    {EXCHANGE_ITEM, "exchangeItem"},
    {GET_INFOS, "getInfos"},
    {KILL, "kill"},
    {ESCAPE, "escape"},
    {ADD_ENTITIES, "addEntities"},
    {GET_HABITANTS, "getHabitants"},
    {GET_EQUIPAGE, "getEquipage"},
    {GET_INVENTORY, "getInventory"},
    {PROMOTE, "promote"},
    {GET_HIERARCHY, "getHierarchy"}
};

typedef enum {
    NONE = -1,
    PLANETE,
    SPACESHIP,
    HEROS,
    PNJ,
    EVIL,
    MISSION,
    ITEM,
    GRADE,
    LIVING
} OBJETS;

typedef  enum {
    AP = 1,
    HP,
    DP,
} EFFECT;

typedef enum {
    UNKWOWN_ERROR = -1,
    UNKNOWN_PLANET,
    UNKNOWN_SPACESHIP,
    UNKNOWN_HEROS,
    UNKNOWN_EVIL,
    UNKNOWN_PNJ,
    UNKNOWN_MISSION,
    UNKNOWN_ITEM,
    UNKNOWN_GRADE,
    UNKNOWN_ENTITY,
    UNKNOWN_COMMAND,

    UNKNOWN_ITEM_SPACECHIP,
    UNKNOWN_ITEM_HEROS,
    UNKNOWN_ITEM_EVIL,
    UNKNOWN_ITEM_PNJ,
    UNKNOWN_DEFENSE_OR_ATTACK,
    UNKNOWN_ID_GRADE,
    UNKNOWN_ACTION,
    UNKNOWN_ATTACK_ACTION,

    NOT_ENOUGHT_ATTRIBUT,
    NOT_ENOUGHT_ATTRIBUT_PLANET,
    NOT_ENOUGHT_ATTRIBUT_SPACESHIP,
    NOT_ENOUGHT_ATTRIBUT_HEROS,
    NOT_ENOUGHT_ATTRIBUT_EVIL,
    NOT_ENOUGHT_ATTRIBUT_PNJ,
    NOT_ENOUGHT_ATTRIBUT_ITEM,
    NOT_ENOUGHT_ATTRIBUT_MISSION,

    MISSING_SECURITY_ATTRIBUT,
    MISSING_COMMAND_ATTRIBUT,
    MISSING_STARTREK_ATTRIBUT,
    MISSING_ENTITY_TYPE_ATTRIBUT,
    MISSING_DEFENSE_ATTRIBUT,
    MISSING_ATTACK_ATTRIBUT,
    MISSING_ENTITY_ID_ATTRIBUT,
    MISSING_ACTION_ATTRIBUT,
    MISSING_ITEMS_ATTRIBUT,
    MISSING_DEFENSE_TYPE_ATTRIBUT,
    MISSING_DEFENSE_ID_ATTRIBUT,
    MISSING_ATTACK_ID_ATTRIBUT,
    MISSING_ATTACK_TYPE_ATTRIBUT,

    MISSING_ID_ATTRIBUT_PLANET,
    MISSING_NAME_ATTRIBUT_PLANET,
    MISSING_DESC_ATTRIBUT_PLANET,

    MISSING_ID_ATTRIBUT_SPACESHIP,
    MISSING_NAME_ATTRIBUT_SPACESHIP,
    MISSING_DESC_ATTRIBUT_SPACESHIP,
    MISSING_AP_ATTRIBUT_SPACESHIP,
    MISSING_DP_ATTRIBUT_SPACESHIP,
    MISSING_HP_ATTRIBUT_SPACESHIP,
    MAX_ITEM_OVERFLOW_SPACESHIP,

    MISSING_ID_ATTRIBUT_HEROS,
    MISSING_NAME_ATTRIBUT_HEROS,
    MISSING_AP_ATTRIBUT_HEROS,
    MISSING_DP_ATTRIBUT_HEROS,
    MISSING_HP_ATTRIBUT_HEROS,
    MISSING_ID_PLANET_ATTRIBUT_HEROS,
    MISSING_ID_SHIP_ATTRIBUT_HEROS,
    MISSING_ID_PLANET_ORIGIN_ATTRIBUT_HEROS,
    MISSING_ID_GRADE_ATTRIBUT_HEROS,
    MAX_ITEM_OVERFLOW_HEROS,

    MISSING_ID_ATTRIBUT_EVIL,
    MISSING_NAME_ATTRIBUT_EVIL,
    MISSING_AP_ATTRIBUT_EVIL,
    MISSING_DP_ATTRIBUT_EVIL,
    MISSING_HP_ATTRIBUT_EVIL,
    MISSING_ID_PLANET_ATTRIBUT_EVIL,
    MISSING_ID_SHIP_ATTRIBUT_EVIL,
    MISSING_ID_PLANET_ORIGIN_ATTRIBUT_EVIL,
    MISSING_ID_GRADE_ATTRIBUT_EVIL,
    MAX_ITEM_OVERFLOW_EVIL,

    MISSING_ID_ATTRIBUT_PNJ,
    MISSING_NAME_ATTRIBUT_PNJ,
    MISSING_AP_ATTRIBUT_PNJ,
    MISSING_DP_ATTRIBUT_PNJ,
    MISSING_HP_ATTRIBUT_PNJ,
    MISSING_ID_PLANET_ATTRIBUT_PNJ,
    MISSING_ID_SHIP_ATTRIBUT_PNJ,
    MISSING_ID_PLANET_ORIGIN_ATTRIBUT_PNJ,
    MISSING_ID_GRADE_ATTRIBUT_PNJ,
    MAX_ITEM_OVERFLOW_PNJ,

    MISSING_ID_ATTRIBUT_MISSION,
    MISSING_NAME_ATTRIBUT_MISSION,
    MISSING_DESC_ATTRIBUT_MISSION,
    MISSING_IS_COMPLETE_ATTRIBUT_MISSION,

    MISSING_ID_ATTRIBUT_ITEM,
    MISSING_NAME_ATTRIBUT_ITEM,
    MISSING_STAT_ATTRIBUT_ITEM,
    MISSING_EFFECT_ATTRIBUT_ITEM,
    MISSING_ID_OWNER_ATTRIBUT_ITEM,
    MISSING_TYPE_OWNER_ATTRIBUT_ITEM,

    MISSING_ID_ATTRIBUT_GRADE,
    MISSING_NAME_ATTRIBUT_GRADE,
    MISSING_LEVEL_ATTRIBUT_GRADE,

    MISSING_INVENTORY,
    MISSING_GRADE,
    JSON_SYNTAXE_ERROR,
    ITEM_OCCUPY,
    INCORRECT_PASSWORD,
    ENTITY_OUT_RANGE,
    
}   CODE_ERROR;

#endif //CPP_STAR_TREK_DEFINE_H
